version: '{build}'

environment:
    global:
        CYG_ROOT: C:\cygwin64
        CYG_MIRROR: http://cygwin.mirror.constant.com
        CYG_CACHE: C:\cygwin64\var\cache\setup
        CYG_BASH: C:\cygwin64\bin\bash

cache:
  - '%CYG_CACHE%'

install:
    - '%CYG_ROOT%\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages autoconf,autogen,automake,cygwin-devel,git,gcc-core,gcc-g++,libncurses-devel,libprotobuf-devel,make,openssh,openssl-devel,perl,perl_pods,pkg-config,tmux,zlib-devel'
    - '%CYG_ROOT%\bin\cygcheck -dc cygwin'

branches:
    only:
    - master
image:
- Visual Studio 2017
configuration:
- RelWithDebInfo
platform:
- x64

before_build:
- cmd: |-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    cd c:\projects
    cd llvm-project
    mkdir build
    cd build
    cmake --version
    %CYG_BASH% -lc "source /cygdrive/c/projects/llvm-project/build.sh"

build_script:
    echo "Build Script"

artifacts:
    - path: c:/projects/llvm-project/build/RelWithDebInfo/*
      name: ClangBinaries 

after_build:
    echo "After Build"
     
before_test:
    echo "Before Test"

test_script:
    echo "Test Script"

after_test:
    echo "After Test"
