name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: | 
            mkdir build
            cd build
            pwd
            cmake -G "Unix Makefiles" ../llvm -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DCMAKE_BUILD_TYPE=Release
            make clang-format -j4
            make FormatTests -j4

